In [16]:
import pandas as pd
import sklearn
n='TargetDataBasecsv.csv'
m='completedclient.csv'
df1=pd.read_csv(m)
df=pd.read_csv(n)

In [17]:
ym=df.columns.values.tolist()
ym

['Acct_id',
 'Acct_UIDNo.',
 'Acct_FName',
 'Acct_MName',
 'Acct_LName',
 'Acct_Addr1',
 'Acct_Addr2',
 'Acct_City',
 'Acct_State',
 'Acct_phone',
 'Acct_email',
 'Acct_DOB',
 'Acct_Gender']

In [18]:
ym1=df1.columns.values.tolist()
ym1

['client_id',
 'sex',
 'fulldate',
 'day',
 'month',
 'year',
 'age',
 'social',
 'first',
 'middle',
 'last',
 'phone',
 'email',
 'address_1',
 'address_2',
 'city',
 'state',
 'zipcode',
 'district_id']

In [5]:
from sklearn.preprocessing import LabelEncoder
Le=LabelEncoder()

In [6]:
df_final=Le.fit_transform(ym)
df_final

array([11,  9,  4,  7,  6,  0,  1,  2,  8, 12, 10,  3,  5], dtype=int64)

In [7]:
df1_final=Le.fit_transform(ym1)
df1_final

array([ 4, 14,  9,  5, 12, 17,  2, 15,  8, 11, 10, 13,  7,  0,  1,  3, 16,
       18,  6], dtype=int64)

In [8]:
dfd = pd.DataFrame(df_final, columns=['Target Table'])
ym= pd.DataFrame(ym,columns=['Target name'])
dfd=pd.merge(ym,dfd,right_index=True, left_index=True)
dfd

    Target name  Target Table
0       Acct_id            11
1   Acct_UIDNo.             9
2    Acct_FName             4
3    Acct_MName             7
4    Acct_LName             6
5    Acct_Addr1             0
6    Acct_Addr2             1
7     Acct_City             2
8    Acct_State             8
9    Acct_phone            12
10   Acct_email            10
11     Acct_DOB             3
12  Acct_Gender             5

In [9]:
df1d = pd.DataFrame(df1_final, columns=['Test Table'])
ym1= pd.DataFrame(ym1,columns=['Test name'])
df1d=pd.merge(ym1,df1d,right_index=True, left_index=True)
df1d

      Test name  Test Table
0     client_id           4
1           sex          14
2      fulldate           9
3           day           5
4         month          12
5          year          17
6           age           2
7        social          15
8         first           8
9        middle          11
10         last          10
11        phone          13
12        email           7
13    address_1           0
14    address_2           1
15         city           3
16        state          16
17      zipcode          18
18  district_id           6

In [10]:
df_final=df_final.tolist()
df_final

[11, 9, 4, 7, 6, 0, 1, 2, 8, 12, 10, 3, 5]

In [11]:
df1_final=df1_final.tolist()
df1_final

[4, 14, 9, 5, 12, 17, 2, 15, 8, 11, 10, 13, 7, 0, 1, 3, 16, 18, 6]

In [12]:
from sklearn.metrics.pairwise import cosine_similarity,cosine_distances
cosine_similarity([df_final],[df1_final])

ValueError: Incompatible dimension for X and Y matrices: X.shape[1] == 13 while Y.shape[1] == 19

In [13]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')

In [14]:
enc_df = pd.DataFrame(enc.fit_transform(dfd[['Target Table']]).toarray())

In [15]:
dfd = dfd.join(enc_df)

dfd

,Target name,Target Table,0,1,2,3,4,5,6,7,8,9,10,11,12
0,Acct_id,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,Acct_UIDNo.,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,Acct_FName,4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Acct_MName,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,Acct_LName,6,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5,Acct_Addr1,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,Acct_Addr2,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,Acct_City,2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,Acct_State,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
9,Acct_phone,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10,Acct_email,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
11,Acct_DOB,3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,Acct_Gender,5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
dfd=dfd.drop(columns=['Target name'],axis=1)
dfd

,Target Table,0,1,2,3,4,5,6,7,8,9,10,11,12
0,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,6,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
9,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
11,3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
enc_df1 = pd.DataFrame(enc.fit_transform(df1d[['Test Table']]).toarray())
enc_df1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
6,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
18,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
df1d = df1d.join(enc_df1)
df1d

,Test name,Test Table,0,1,2,3,4,5,6,7,...,9,10,11,12,13,14,15,16,17,18
0,client_id,4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,sex,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,fulldate,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,day,5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,month,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5,year,17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
6,age,2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,social,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
8,first,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,middle,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,last,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,phone,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
12,email,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,address_1,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,address_2,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,city,3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,state,16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
17,zipcode,18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
18,district_id,6,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
df1d.drop(columns=['Test name'],axis=1)
df1d

,Test name,Test Table,0,1,2,3,4,5,6,7,...,9,10,11,12,13,14,15,16,17,18
0,client_id,4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,sex,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,fulldate,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,day,5,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,month,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5,year,17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
6,age,2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,social,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
8,first,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,middle,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,last,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,phone,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
12,email,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,address_1,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,address_2,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,city,3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,state,16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
17,zipcode,18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
18,district_id,6,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer()
vec.fit_transform(n).toarray()

AttributeError: 'str' object has no attribute 'items'

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

In [120]:
vectorizer = CountVectorizer()

In [121]:
X = vectorizer.fit_transform(ym)

In [122]:
X

<13x13 sparse matrix of type '<class 'numpy.int64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [123]:
X.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [128]:
Y = vectorizer.fit_transform(ym1)

In [129]:
Y

<19x19 sparse matrix of type '<class 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [130]:
Y.toarray()

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [134]:
sklearn.metrics.pairwise.cosine_distances(X,Y)

ValueError: Incompatible dimension for X and Y matrices: X.shape[1] == 13 while Y.shape[1] == 19

In [24]:
pip install segmentation-models

Collecting segmentation-models
  Downloading segmentation_models-1.0.1-py3-none-any.whl (33 kB)
Collecting image-classifiers==1.0.0
  Downloading image_classifiers-1.0.0-py3-none-any.whl (19 kB)
Collecting keras-applications<=1.0.8,>=1.0.7
  Downloading Keras_Applications-1.0.8-py3-none-any.whl (50 kB)
Collecting efficientnet==1.0.0
  Downloading efficientnet-1.0.0-py3-none-any.whl (17 kB)
Collecting scikit-image
  Downloading scikit_image-0.18.2-cp39-cp39-win_amd64.whl (12.2 MB)
Requirement already satisfied: numpy>=1.9.1 in c:\python\python39\lib\site-packages (from keras-applications<=1.0.8,>=1.0.7->segmentation-models) (1.20.2)
Collecting h5py
  Downloading h5py-3.3.0-cp39-cp39-win_amd64.whl (2.8 MB)
Collecting tifffile>=2019.7.26
  Downloading tifffile-2021.7.2-py3-none-any.whl (169 kB)
Collecting PyWavelets>=1.1.1
  Downloading PyWavelets-1.1.1-cp39-cp39-win_amd64.whl (4.2 MB)
Requirement already satisfied: pillow!=7.1.0,!=7.1.1,>=4.3.0 in c:\python\python39\lib\site-packages (from scikit-image->efficientnet==1.0.0->segmentation-models) (8.2.0)
Requirement already satisfied: networkx>=2.0 in c:\python\python39\lib\site-packages (from scikit-image->efficientnet==1.0.0->segmentation-models) (2.5.1)
Collecting imageio>=2.3.0
  Downloading imageio-2.9.0-py3-none-any.whl (3.3 MB)
Requirement already satisfied: scipy>=1.0.1 in c:\python\python39\lib\site-packages (from scikit-image->efficientnet==1.0.0->segmentation-models) (1.6.3)
Requirement already satisfied: matplotlib!=3.0.0,>=2.0.0 in c:\python\python39\lib\site-packages (from scikit-image->efficientnet==1.0.0->segmentation-models) (3.4.2)
Requirement already satisfied: pyparsing>=2.2.1 in c:\python\python39\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->efficientnet==1.0.0->segmentation-models) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\python\python39\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->efficientnet==1.0.0->segmentation-models) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\python\python39\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->efficientnet==1.0.0->segmentation-models) (0.10.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\python\python39\lib\site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image->efficientnet==1.0.0->segmentation-models) (2.8.1)
Requirement already satisfied: six in c:\python\python39\lib\site-packages (from cycler>=0.10->matplotlib!=3.0.0,>=2.0.0->scikit-image->efficientnet==1.0.0->segmentation-models) (1.15.0)
Requirement already satisfied: decorator<5,>=4.3 in c:\python\python39\lib\site-packages (from networkx>=2.0->scikit-image->efficientnet==1.0.0->segmentation-models) (4.4.2)
Installing collected packages: tifffile, PyWavelets, imageio, h5py, scikit-image, keras-applications, image-classifiers, efficientnet, segmentation-models
Successfully installed PyWavelets-1.1.1 efficientnet-1.0.0 h5py-3.3.0 image-classifiers-1.0.0 imageio-2.9.0 keras-applications-1.0.8 scikit-image-0.18.2 segmentation-models-1.0.1 tifffile-2021.7.2
Note: you may need to restart the kernel to use updated packages.

In [1]:
import tensorflow

ModuleNotFoundError: No module named 'tensorflow'

In [4]:
import tensorflow

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [21]:
vectorizer = TfidfVectorizer()

In [22]:
X = vectorizer.fit_transform(ym)

In [23]:
print(vectorizer.get_feature_names())

['acct_addr1', 'acct_addr2', 'acct_city', 'acct_dob', 'acct_email', 'acct_fname', 'acct_gender', 'acct_id', 'acct_lname', 'acct_mname', 'acct_phone', 'acct_state', 'acct_uidno']

In [24]:
print(X.shape)

(13, 13)

In [27]:
X.toarray()

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [12]:
pip install keras

Collecting keras
  Downloading Keras-2.4.3-py2.py3-none-any.whl (36 kB)
Requirement already satisfied: scipy>=0.14 in c:\python\python39\lib\site-packages (from keras) (1.6.3)
Collecting pyyaml
  Using cached PyYAML-5.4.1-cp39-cp39-win_amd64.whl (213 kB)
Requirement already satisfied: h5py in c:\python\python39\lib\site-packages (from keras) (3.1.0)
Requirement already satisfied: numpy>=1.9.1 in c:\python\python39\lib\site-packages (from keras) (1.19.5)
Installing collected packages: pyyaml, keras
Successfully installed keras-2.4.3 pyyaml-5.4.1
Note: you may need to restart the kernel to use updated packages.

In [28]:
from tensorflow.keras.preprocessing.text import one_hot

In [29]:
voc_size=10000

In [30]:
onehot_repr=[one_hot(words,voc_size)for words in ym] 
print(onehot_repr)

[[4307, 8155], [4307, 4147], [4307, 1425], [4307, 741], [4307, 5615], [4307, 9123], [4307, 5719], [4307, 2219], [4307, 1648], [4307, 7214], [4307, 355], [4307, 1316], [4307, 5097]]

In [31]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [32]:
import numpy as np

In [33]:
sent_length=2
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[4307 8155]
 [4307 4147]
 [4307 1425]
 [4307  741]
 [4307 5615]
 [4307 9123]
 [4307 5719]
 [4307 2219]
 [4307 1648]
 [4307 7214]
 [4307  355]
 [4307 1316]
 [4307 5097]]

In [34]:
dim=10

In [35]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
embedding (Embedding)        (None, 2, 10)             100000
=================================================================
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________

In [47]:
df_final=model.predict(embedded_docs)
print(df_final)

[[[ 0.00578276 -0.04946172  0.00538149 -0.02848188 -0.04883781
   -0.03938277 -0.02549856 -0.03836586  0.01307083 -0.01025629]
  [ 0.04475224  0.00354111  0.0314566  -0.03939313 -0.03765974
    0.00128193 -0.00927861 -0.02903291 -0.04850748 -0.04003046]]

 [[ 0.00578276 -0.04946172  0.00538149 -0.02848188 -0.04883781
   -0.03938277 -0.02549856 -0.03836586  0.01307083 -0.01025629]
  [-0.01575165 -0.00300013  0.00647368  0.01958651  0.00692167
   -0.00864118 -0.03192033  0.03577782  0.0443342  -0.02415438]]

 [[ 0.00578276 -0.04946172  0.00538149 -0.02848188 -0.04883781
   -0.03938277 -0.02549856 -0.03836586  0.01307083 -0.01025629]
  [-0.02499528  0.00997872  0.03277255  0.02308711 -0.03653344
   -0.02845057 -0.0314128   0.03120086 -0.00882689  0.01561325]]

 [[ 0.00578276 -0.04946172  0.00538149 -0.02848188 -0.04883781
   -0.03938277 -0.02549856 -0.03836586  0.01307083 -0.01025629]
  [ 0.03892717  0.04582204 -0.03350043 -0.02023629  0.03114953
    0.01247931 -0.02132297 -0.00857488 -0.04667255 -0.03637518]]

 [[ 0.00578276 -0.04946172  0.00538149 -0.02848188 -0.04883781
   -0.03938277 -0.02549856 -0.03836586  0.01307083 -0.01025629]
  [-0.04636269 -0.0123778   0.00233772  0.00516934  0.01594658
   -0.0325468   0.02963397 -0.00083758  0.04912262  0.01265385]]

 [[ 0.00578276 -0.04946172  0.00538149 -0.02848188 -0.04883781
   -0.03938277 -0.02549856 -0.03836586  0.01307083 -0.01025629]
  [ 0.00660554 -0.04850477 -0.04588516 -0.04813526  0.02845867
    0.00018418 -0.03935413 -0.04061412  0.03337726  0.03674035]]

 [[ 0.00578276 -0.04946172  0.00538149 -0.02848188 -0.04883781
   -0.03938277 -0.02549856 -0.03836586  0.01307083 -0.01025629]
  [-0.04830083  0.00399525  0.04463509 -0.00032552  0.01497269
    0.02175776 -0.02705834  0.04067189  0.04977283  0.01162947]]

 [[ 0.00578276 -0.04946172  0.00538149 -0.02848188 -0.04883781
   -0.03938277 -0.02549856 -0.03836586  0.01307083 -0.01025629]
  [-0.04978684  0.04029253 -0.04695213 -0.02203187 -0.00556134
   -0.00449517 -0.02422253 -0.03179621  0.04740652 -0.02689447]]

 [[ 0.00578276 -0.04946172  0.00538149 -0.02848188 -0.04883781
   -0.03938277 -0.02549856 -0.03836586  0.01307083 -0.01025629]
  [-0.00737183  0.01762645 -0.04651766  0.01495894  0.04419888
    0.02269134  0.04043081 -0.03901035 -0.04737912  0.03466438]]

 [[ 0.00578276 -0.04946172  0.00538149 -0.02848188 -0.04883781
   -0.03938277 -0.02549856 -0.03836586  0.01307083 -0.01025629]
  [-0.00542565 -0.04153931  0.04403374 -0.01117577 -0.01334678
   -0.03919271 -0.01406567 -0.04336787  0.00524608  0.01317693]]

 [[ 0.00578276 -0.04946172  0.00538149 -0.02848188 -0.04883781
   -0.03938277 -0.02549856 -0.03836586  0.01307083 -0.01025629]
  [ 0.0411385  -0.01108922 -0.01080883 -0.02394019  0.03054671
   -0.03577641  0.03255758 -0.04448826 -0.02859255  0.03100992]]

 [[ 0.00578276 -0.04946172  0.00538149 -0.02848188 -0.04883781
   -0.03938277 -0.02549856 -0.03836586  0.01307083 -0.01025629]
  [-0.02653073  0.04217294  0.04796777  0.02659199 -0.04663496
    0.00887697 -0.02329848 -0.00943706  0.01992841  0.01094929]]

 [[ 0.00578276 -0.04946172  0.00538149 -0.02848188 -0.04883781
   -0.03938277 -0.02549856 -0.03836586  0.01307083 -0.01025629]
  [ 0.04800464 -0.01442314 -0.04046261 -0.01382471  0.0020098
    0.04092474  0.03785168 -0.03454176 -0.04111931  0.02610847]]]

In [37]:
embedded_docs[0]

array([4307, 8155])

In [40]:
print(model.predict(embedded_docs)[0])

[[ 0.04860908 -0.04942579 -0.02701199 -0.02313532 -0.02505285  0.04244756
   0.04994459  0.02407591  0.01944577 -0.00658996]
 [ 0.03268505  0.04199691  0.04895972  0.01470277  0.04541311 -0.00182579
  -0.02423388  0.02329422 -0.01014798  0.008566  ]]

In [42]:
onehot_repr1=[one_hot(words,voc_size)for words in ym1] 
print(onehot_repr1)

[[9220, 8155], [2224], [2412], [409], [3339], [6003], [3897], [2761], [4707], [5978], [3178], [7214], [355], [3816, 2166], [3816, 8711], [2219], [1648], [501], [6243, 8155]]

In [43]:
sent_length=2
embedded_docs1=pad_sequences(onehot_repr1,padding='pre',maxlen=sent_length)
print(embedded_docs1)

[[9220 8155]
 [   0 2224]
 [   0 2412]
 [   0  409]
 [   0 3339]
 [   0 6003]
 [   0 3897]
 [   0 2761]
 [   0 4707]
 [   0 5978]
 [   0 3178]
 [   0 7214]
 [   0  355]
 [3816 2166]
 [3816 8711]
 [   0 2219]
 [   0 1648]
 [   0  501]
 [6243 8155]]

In [44]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [48]:
df_final1=model.predict(embedded_docs1)
df_final1

array([[[ 0.0234515 ,  0.00030862,  0.0168777 ,  0.00742185,
          0.03254129, -0.03058815, -0.01384569, -0.02054203,
          0.01623074,  0.04514182],
        [ 0.04475224,  0.00354111,  0.0314566 , -0.03939313,
         -0.03765974,  0.00128193, -0.00927861, -0.02903291,
         -0.04850748, -0.04003046]],

       [[-0.03833247,  0.00802621, -0.04797062,  0.01530607,
         -0.03867797,  0.04818765, -0.03464483,  0.01545468,
          0.0149571 , -0.02701794],
        [-0.00408828,  0.00422912,  0.04966784,  0.01093168,
         -0.03776255, -0.0094367 , -0.0010892 ,  0.01323842,
         -0.0132582 , -0.02116332]],

       [[-0.03833247,  0.00802621, -0.04797062,  0.01530607,
         -0.03867797,  0.04818765, -0.03464483,  0.01545468,
          0.0149571 , -0.02701794],
        [-0.04243771,  0.04103725,  0.0175286 ,  0.03982917,
         -0.04186244,  0.00060339, -0.00439788,  0.0052686 ,
          0.03604833,  0.04614092]],

       [[-0.03833247,  0.00802621, -0.04797062,  0.01530607,
         -0.03867797,  0.04818765, -0.03464483,  0.01545468,
          0.0149571 , -0.02701794],
        [-0.01908524,  0.04148859, -0.00559156, -0.02867324,
          0.04735476, -0.01039716, -0.01989046, -0.04216155,
          0.03378058,  0.00141972]],

       [[-0.03833247,  0.00802621, -0.04797062,  0.01530607,
         -0.03867797,  0.04818765, -0.03464483,  0.01545468,
          0.0149571 , -0.02701794],
        [-0.02770802,  0.00017469,  0.04462122,  0.0138814 ,
         -0.02081876, -0.04386714, -0.04995474, -0.03151146,
          0.00382972,  0.04279289]],

       [[-0.03833247,  0.00802621, -0.04797062,  0.01530607,
         -0.03867797,  0.04818765, -0.03464483,  0.01545468,
          0.0149571 , -0.02701794],
        [ 0.01615553,  0.00539954, -0.01609813, -0.01535872,
         -0.0026873 , -0.00141652, -0.02570059, -0.01855367,
          0.03195131, -0.02716237]],

       [[-0.03833247,  0.00802621, -0.04797062,  0.01530607,
         -0.03867797,  0.04818765, -0.03464483,  0.01545468,
          0.0149571 , -0.02701794],
        [ 0.00394235, -0.00315128,  0.0159037 ,  0.04037211,
          0.00875701, -0.00429462,  0.02531828, -0.02218629,
         -0.03554868,  0.00256262]],

       [[-0.03833247,  0.00802621, -0.04797062,  0.01530607,
         -0.03867797,  0.04818765, -0.03464483,  0.01545468,
          0.0149571 , -0.02701794],
        [-0.02697918, -0.01026107, -0.03072901,  0.00999192,
          0.03879274,  0.00934001,  0.01394028, -0.01864193,
         -0.01237974, -0.04898461]],

       [[-0.03833247,  0.00802621, -0.04797062,  0.01530607,
         -0.03867797,  0.04818765, -0.03464483,  0.01545468,
          0.0149571 , -0.02701794],
        [-0.04476795, -0.01274694,  0.01523563,  0.02533511,
         -0.0422237 ,  0.00314607,  0.02158428, -0.01916372,
          0.00185497, -0.00676968]],

       [[-0.03833247,  0.00802621, -0.04797062,  0.01530607,
         -0.03867797,  0.04818765, -0.03464483,  0.01545468,
          0.0149571 , -0.02701794],
        [-0.03049701, -0.03696773, -0.00680611, -0.0186342 ,
          0.01972559, -0.0079608 , -0.02185684,  0.00010561,
         -0.01576293, -0.04568422]],

       [[-0.03833247,  0.00802621, -0.04797062,  0.01530607,
         -0.03867797,  0.04818765, -0.03464483,  0.01545468,
          0.0149571 , -0.02701794],
        [ 0.03826581,  0.04998885,  0.02485675, -0.03754552,
         -0.04804737, -0.03995102, -0.04883843, -0.00580168,
          0.00655486,  0.02851686]],

       [[-0.03833247,  0.00802621, -0.04797062,  0.01530607,
         -0.03867797,  0.04818765, -0.03464483,  0.01545468,
          0.0149571 , -0.02701794],
        [-0.00542565, -0.04153931,  0.04403374, -0.01117577,
         -0.01334678, -0.03919271, -0.01406567, -0.04336787,
          0.00524608,  0.01317693]],

       [[-0.03833247,  0.00802621, -0.04797062,  0.01530607,
         -0.03867797,  0.04818765, -0.03464483,  0.01545468,
          0.0149571 , -0.02701794],
        [ 0.0411385 , -0.01108922, -0.01080883, -0.02394019,
          0.03054671, -0.03577641,  0.03255758, -0.04448826,
         -0.02859255,  0.03100992]],

       [[ 0.04058312,  0.03300408, -0.03221866, -0.0433614 ,
          0.03238774, -0.04291493, -0.02854356,  0.00915831,
          0.03750186,  0.03825548],
        [ 0.01222108, -0.01405711, -0.04866819, -0.01902274,
         -0.01827411, -0.03773367, -0.00696875, -0.02809212,
         -0.00119511, -0.02069405]],

       [[ 0.04058312,  0.03300408, -0.03221866, -0.0433614 ,
          0.03238774, -0.04291493, -0.02854356,  0.00915831,
          0.03750186,  0.03825548],
        [ 0.02470443, -0.03050995,  0.04269078,  0.02704747,
          0.00904685,  0.0383018 ,  0.03070762,  0.03100852,
          0.02653053,  0.02653332]],

       [[-0.03833247,  0.00802621, -0.04797062,  0.01530607,
         -0.03867797,  0.04818765, -0.03464483,  0.01545468,
          0.0149571 , -0.02701794],
        [-0.04978684,  0.04029253, -0.04695213, -0.02203187,
         -0.00556134, -0.00449517, -0.02422253, -0.03179621,
          0.04740652, -0.02689447]],

       [[-0.03833247,  0.00802621, -0.04797062,  0.01530607,
         -0.03867797,  0.04818765, -0.03464483,  0.01545468,
          0.0149571 , -0.02701794],
        [-0.00737183,  0.01762645, -0.04651766,  0.01495894,
          0.04419888,  0.02269134,  0.04043081, -0.03901035,
         -0.04737912,  0.03466438]],

       [[-0.03833247,  0.00802621, -0.04797062,  0.01530607,
         -0.03867797,  0.04818765, -0.03464483,  0.01545468,
          0.0149571 , -0.02701794],
        [ 0.0355817 ,  0.03598419,  0.01234919, -0.02526662,
         -0.00835054, -0.02981943, -0.04150943, -0.00554665,
         -0.03796839,  0.03882346]],

       [[ 0.00293941, -0.04135196, -0.03140122,  0.00857057,
          0.0144233 , -0.02116892,  0.00615268, -0.03582157,
         -0.03751639,  0.03489381],
        [ 0.04475224,  0.00354111,  0.0314566 , -0.03939313,
         -0.03765974,  0.00128193, -0.00927861, -0.02903291,
         -0.04850748, -0.04003046]]], dtype=float32)

In [50]:
from sklearn.metrics.pairwise import cosine_similarity,cosine_distances
cosine_similarity(embedded_docs1,embedded_docs)

array([[0.93564668, 0.99910571, 0.91923638, 0.85053097, 0.98156901,
        0.9188918 , 0.97984105, 0.96929717, 0.93634202, 0.95282618,
        0.80093466, 0.90994708, 0.9895018 ],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880838, 0.45799613, 0.3573656 , 0.85861457,
        0.0821454 , 0.29221289, 0.76381811],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880838, 0.45799613, 0.3573656 , 0.85861457,
        0.0821454 , 0.29221289, 0.76381811],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880838, 0.45799613, 0.3573656 , 0.85861457,
        0.0821454 , 0.29221289, 0.76381811],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880838, 0.45799613, 0.3573656 , 0.85861457,
        0.0821454 , 0.29221289, 0.76381811],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880838, 0.45799613, 0.3573656 , 0.85861457,
        0.0821454 , 0.29221289, 0.76381811],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880838, 0.45799613, 0.3573656 , 0.85861457,
        0.0821454 , 0.29221289, 0.76381811],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880838, 0.45799613, 0.3573656 , 0.85861457,
        0.0821454 , 0.29221289, 0.76381811],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880838, 0.45799613, 0.3573656 , 0.85861457,
        0.0821454 , 0.29221289, 0.76381811],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880838, 0.45799613, 0.3573656 , 0.85861457,
        0.0821454 , 0.29221289, 0.76381811],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880838, 0.45799613, 0.3573656 , 0.85861457,
        0.0821454 , 0.29221289, 0.76381811],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880838, 0.45799613, 0.3573656 , 0.85861457,
        0.0821454 , 0.29221289, 0.76381811],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880838, 0.45799613, 0.3573656 , 0.85861457,
        0.0821454 , 0.29221289, 0.76381811],
       [0.84264142, 0.96886003, 0.98070848, 0.94077569, 0.92098005,
        0.8176661 , 0.91749948, 0.99917905, 0.98864864, 0.86965264,
        0.90728059, 0.97595788, 0.93835868],
       [0.99733515, 0.92436225, 0.66866064, 0.55075092, 0.97099477,
        0.99960251, 0.97307073, 0.77620607, 0.70209249, 0.99215405,
        0.4751409 , 0.65139837, 0.95861422],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880838, 0.45799613, 0.3573656 , 0.85861457,
        0.0821454 , 0.29221289, 0.76381811],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880838, 0.45799613, 0.3573656 , 0.85861457,
        0.0821454 , 0.29221289, 0.76381811],
       [0.88425168, 0.6935999 , 0.31411086, 0.16955443, 0.7934585 ,
        0.9042901 , 0.79880838, 0.45799613, 0.3573656 , 0.85861457,
        0.0821454 , 0.29221289, 0.76381811],
       [0.9860101 , 0.98862905, 0.82651844, 0.73370033, 0.99999955,
        0.97755055, 0.99996888, 0.90403386, 0.85148991, 0.99337883,
        0.67104137, 0.81336566, 0.99883794]])

In [51]:
from sklearn.metrics.pairwise import euclidean_distances
euclidean_distances(embedded_docs1,embedded_docs)

array([[4913.        , 6340.47577079, 8332.49476447, 8894.09719983,
        5530.74759865, 5007.45374417, 5483.76376223, 7705.43087699,
        8153.44209521, 5002.30446894, 9218.32788525, 8420.77728004,
        5786.96232924],
       [7329.87107663, 4716.79743046, 4380.48513295, 4555.1660782 ,
        5481.70867522, 8133.04678457, 5546.64529243, 4307.00290225,
        4345.34521068, 6591.68787186, 4695.04100089, 4401.67161428,
        5177.29446719],
       [7178.60000279, 4643.32574778, 4418.64436225, 4619.79328542,
        5367.44427079, 7974.19400316, 5430.14714349, 4311.32207101,
        4374.23650481, 6450.53896973, 4772.99675257, 4444.26203098,
        5075.37919766],
       [8862.88694501, 5702.88462096, 4425.21242428, 4319.77696183,
        6756.67706791, 9720.29037632, 6837.13017281, 4671.86782775,
        4481.6704475 , 8053.46347853, 4307.33850539, 4401.46543778,
        6366.12857237],
       [6460.96780676, 4382.13566654, 4713.13536831, 5029.89592338,
        4871.38840578, 7211.44264347, 4920.8382416 , 4450.24145412,
        4627.06494443, 5793.6063035 , 5239.70466725, 4758.44281252,
        4651.96872302],
       [4814.70175608, 4689.88112856, 6285.56544791, 6799.91860245,
        4324.4413512 , 5318.33141126, 4316.35320612, 5733.14093669,
        6125.05297936, 4474.01050513, 7102.8271132 , 6365.39221101,
        4401.25947883],
       [6056.46869058, 4314.24952918, 4965.98761577, 5339.53041006,
        4637.00043131, 6772.09900991, 4676.53001701, 4622.3298238 ,
        4858.83216421, 5436.24300413, 5576.37991891, 5021.13632557,
        4471.04562714],
       [6902.57089786, 4524.51599621, 4509.45063173, 4757.16817025,
        5166.77510639, 7682.79200551, 5224.94143508, 4340.96913143,
        4448.48491062, 6195.11565671, 4933.46582029, 4542.93671539,
        4899.70866481],
       [5517.15080454, 4343.25327376, 5414.95826392, 5854.86165507,
        4401.67161428, 6168.57398432, 4424.29576317, 4973.97155199,
        5282.77673198, 4983.50258352, 6122.92029999, 5481.70867522,
        4324.62125509],
       [4825.92768284, 4680.04380321, 6267.38047353, 6780.59127215,
        4322.27000545, 5333.03609588, 4314.78041156, 5716.67123421,
        6107.30292355, 4480.84199677, 7082.96392762, 6347.0066173 ,
        4396.18129744],
       [6581.85217093, 4414.65853719, 4650.08150466, 4948.65820198,
        4948.65820198, 7341.20385223, 5000.69295198, 4412.47436253,
        4570.6836469 , 5902.50328251, 5149.71630287, 4692.2588377 ,
        4715.1680776 ],
       [4408.59728258, 5287.41316714, 7215.4535547 , 7774.95839217,
        4594.24096016, 4711.10708857, 4559.08697   , 6595.47375099,
        7037.79830629, 4307.        , 8099.14378191, 7303.19471191,
        4799.16013486],
       [8910.12059402, 5738.42426107, 4437.92169827, 4324.26236484,
        6798.37105489, 9768.72934419, 6879.1529275 , 4693.05284436,
        4496.89870911, 8099.14378191, 4307.        , 4412.90947109,
        6405.99820481],
       [6009.09327603, 2040.94144943,  888.91056918, 1507.21796698,
        3483.77410289, 6974.30498329, 3586.76595278,  493.85220461,
         713.72613795, 5071.82265068, 1876.38002547,  981.62161753,
        2971.84151664],
       [ 741.76613565, 4590.33517295, 7302.5253851 , 7985.10995541,
        3134.69248891,  640.95631676, 3032.01995376, 6510.54106814,
        7080.04590381, 1575.46501072, 8370.41319171, 7411.28234518,
        3647.20125576],
       [7333.91743886, 4718.83809852, 4379.57589271, 4553.54071026,
        5484.80309583, 8137.28855332, 5549.7972035 , 4307.        ,
        4344.68525903, 6595.47375099, 4693.05284436, 4400.64290758,
        5180.07075241],
       [7803.28764048, 4979.48290488, 4312.76918   , 4401.46543778,
        5855.53908705, 8627.04317829, 5926.49052982, 4344.68525903,
        4307.        , 7037.79830629, 4496.89870911, 4319.77696183,
        5517.77582002],
       [8782.59443445, 5643.01027821, 4405.        , 4313.68160624,
        6686.04853407, 9637.90086066, 6765.92735699, 4637.00043131,
        4457.11319129, 7975.87725583, 4309.4738658 , 4383.43176062,
        6298.68756171],
       [1936.        , 4451.08526092, 7002.92767348, 7662.60347402,
        3193.69629113, 2164.51380222, 3111.62208502, 6243.73221719,
        6788.89865884, 2152.5745051 , 8036.67194801, 7107.74345345,
        3619.31761524]])